---
mcu:
  type:  STM32F
  class: stm32

motor:
  - name:     MOTOR0
    enable:   PF14
    step:     PF13
    dir:      PF12
  - name:     MOTOR1
    enable:   PF15
    step:     PG0
    dir:      PG1
  - name:     MOTOR2
    enable:   PG5
    step:     PF11
    dir:      PG3
  - name:     MOTOR3
    enable:   PA0
    step:     PG4
    dir:      PC1
  - name:     MOTOR4
    enable:   PG2
    step:     PF9
    dir:      PF10
  - name:     MOTOR5
    enable:   PF1
    step:     PC13
    dir:      PF0
  - name:     MOTOR6
    enable:   PD4
    step:     PE2
    dir:      PE3
  - name:     MOTOR7
    enable:   PE0
    step:     PE6
    dir:      PA14

limit:
  DIAG0:      PG6
  DIAG1:      PG9
  DIAG2:      PG10
  DIAG3:      PG11
  DIAG4:      PG12
  DIAG5:      PG13
  DIAG6:      PG14
  DIAG7:      PG15

fan:
  FAN0:       PA8
  FAN0:       PE5
  FAN2:       PD12
  FAN3:       PD13
  FAN4:       PD14
  FAN5:       PD15

heater:
  HE0:        PA2
  HE1:        PA3
  HE2:        PB10
  HE3:        PB11

heater_bed:
  BED_OUT:    PA1

sensor:
  T0:         PF4
  T1:         PF5
  T2:         PF6
  T3:         PF7

sensor_bed:
  TB:         PF3