---
mcu:
  type:   STM32F446
  class:  stm32
  offset: 0x08000000

motor:
  - name:   X
    enable: PE9
    step:   PE11
    dir:    PE10
    cs:     PE7
  - name:   Y
    enable: PD9
    step:   PD8
    dir:    PB12
    cs:     PE15
  - name:   Z
    enable: PD15
    step:   PD14
    dir:    PD13
    cs:     PD10
  - name:   E0
    enable: PD4
    step:   PD5
    dir:    PD6
    cs:     PD7
  - name:   E1
    enable: PE5
    step:   PE6
    dir:    PC13
    cs:     PC14
  - name:   E2
    enable: PE3
    step:   PE2
    dir:    PE4
    cs:     PC15
  - name:   E3
    enable: PE8
    step:   PD12
    dir:    PC4
    cs:     PA15
  - name:   E4
    enable: PC5
    step:   PE1
    dir:    PE0
    cs:     PD11

spi:
  - name:   SPI4
    mosi:   PE14
    miso:   PE13
    sck:    PE12

limit:
  DIAG_X:   PB14
  DIAG_Y:   PB13
  DIAG_Z:   PA0
  DIAG_E0:  PA1
  DIAG_E1:  PA2
  DIAG_E2:  PA3

fan:
  FAN0:     PB0
  FAN1:     PB1
  FAN2:     PB2
  LED_R:    PB6
  LED_G:    PB5
  LED_B:    PB7

heater:
  HE0:      PB15
  HE1:      PC8
  HE2:      PB3

heater_bed:
  HB:       PB4

sensor:
  TE0:      PC0
  TE1:      PC1
  TE2:      PC2

sensor_bed:
  TB:       PC3

neopixel:   [ PD3 ]

aliases:
  EXP1_1:   PC9
  EXP1_2:   PA8
  EXP1_3:   PC11
  EXP1_4:   PD2
  EXP1_5:   PC10
  EXP1_6:   PC12
  EXP1_7:   PD0
  EXP1_8:   PD1
  EXP1_9:   <GND>
  EXP1_10:  <5V>
  EXP2_1:   PA6
  EXP2_2:   PA5
  EXP2_3:   PC6
  EXP2_4:   PA4
  EXP2_5:   PC7
  EXP2_6:   PA7
  EXP2_7:   PB10
  EXP2_8:   <RST>
  EXP2_9:   <GND>
  EXP2_10:  <5V>
  